/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/odroid/git_laser_scanner/src/laser_scanner/uts_sensor_box/data_recorder/msg/Fs_space.msg
 *
 */


#ifndef DATA_RECORDER_MESSAGE_FS_SPACE_H
#define DATA_RECORDER_MESSAGE_FS_SPACE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace data_recorder
{
template <class ContainerAllocator>
struct Fs_space_
{
  typedef Fs_space_<ContainerAllocator> Type;

  Fs_space_()
    : header()
    , fs_size(0)
    , fs_space(0)  {
    }
  Fs_space_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , fs_size(0)
    , fs_space(0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint64_t _fs_size_type;
  _fs_size_type fs_size;

   typedef uint64_t _fs_space_type;
  _fs_space_type fs_space;




  typedef boost::shared_ptr< ::data_recorder::Fs_space_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::data_recorder::Fs_space_<ContainerAllocator> const> ConstPtr;

}; // struct Fs_space_

typedef ::data_recorder::Fs_space_<std::allocator<void> > Fs_space;

typedef boost::shared_ptr< ::data_recorder::Fs_space > Fs_spacePtr;
typedef boost::shared_ptr< ::data_recorder::Fs_space const> Fs_spaceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::data_recorder::Fs_space_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::data_recorder::Fs_space_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace data_recorder

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'data_recorder': ['/home/odroid/git_laser_scanner/src/laser_scanner/uts_sensor_box/data_recorder/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::data_recorder::Fs_space_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::data_recorder::Fs_space_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::data_recorder::Fs_space_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::data_recorder::Fs_space_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::data_recorder::Fs_space_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::data_recorder::Fs_space_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::data_recorder::Fs_space_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3fb8eb0b826534256f6179d733e3ffbc";
  }

  static const char* value(const ::data_recorder::Fs_space_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3fb8eb0b82653425ULL;
  static const uint64_t static_value2 = 0x6f6179d733e3ffbcULL;
};

template<class ContainerAllocator>
struct DataType< ::data_recorder::Fs_space_<ContainerAllocator> >
{
  static const char* value()
  {
    return "data_recorder/Fs_space";
  }

  static const char* value(const ::data_recorder::Fs_space_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::data_recorder::Fs_space_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
uint64 fs_size\n\
uint64 fs_space\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::data_recorder::Fs_space_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::data_recorder::Fs_space_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.fs_size);
      stream.next(m.fs_space);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Fs_space_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::data_recorder::Fs_space_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::data_recorder::Fs_space_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "fs_size: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.fs_size);
    s << indent << "fs_space: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.fs_space);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DATA_RECORDER_MESSAGE_FS_SPACE_H
