/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/odroid/git_laser_scanner/src/laser_scanner/ble_scanner/msg/BLEBeacon.msg
 *
 */


#ifndef BLE_SCANNER_MESSAGE_BLEBEACON_H
#define BLE_SCANNER_MESSAGE_BLEBEACON_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ble_scanner
{
template <class ContainerAllocator>
struct BLEBeacon_
{
  typedef BLEBeacon_<ContainerAllocator> Type;

  BLEBeacon_()
    : mac_address()
    , rssi(0)  {
    }
  BLEBeacon_(const ContainerAllocator& _alloc)
    : mac_address(_alloc)
    , rssi(0)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mac_address_type;
  _mac_address_type mac_address;

   typedef int16_t _rssi_type;
  _rssi_type rssi;




  typedef boost::shared_ptr< ::ble_scanner::BLEBeacon_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ble_scanner::BLEBeacon_<ContainerAllocator> const> ConstPtr;

}; // struct BLEBeacon_

typedef ::ble_scanner::BLEBeacon_<std::allocator<void> > BLEBeacon;

typedef boost::shared_ptr< ::ble_scanner::BLEBeacon > BLEBeaconPtr;
typedef boost::shared_ptr< ::ble_scanner::BLEBeacon const> BLEBeaconConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ble_scanner::BLEBeacon_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ble_scanner::BLEBeacon_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ble_scanner

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'ble_scanner': ['/home/odroid/git_laser_scanner/src/laser_scanner/ble_scanner/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ble_scanner::BLEBeacon_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ble_scanner::BLEBeacon_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ble_scanner::BLEBeacon_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ble_scanner::BLEBeacon_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ble_scanner::BLEBeacon_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ble_scanner::BLEBeacon_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ble_scanner::BLEBeacon_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b767afad314b67e2e2c82e2bb477f1fe";
  }

  static const char* value(const ::ble_scanner::BLEBeacon_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb767afad314b67e2ULL;
  static const uint64_t static_value2 = 0xe2c82e2bb477f1feULL;
};

template<class ContainerAllocator>
struct DataType< ::ble_scanner::BLEBeacon_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ble_scanner/BLEBeacon";
  }

  static const char* value(const ::ble_scanner::BLEBeacon_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ble_scanner::BLEBeacon_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string mac_address # MAC address of an access point\n\
int16 rssi         # signal strength [RSSI]\n\
";
  }

  static const char* value(const ::ble_scanner::BLEBeacon_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ble_scanner::BLEBeacon_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mac_address);
      stream.next(m.rssi);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct BLEBeacon_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ble_scanner::BLEBeacon_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ble_scanner::BLEBeacon_<ContainerAllocator>& v)
  {
    s << indent << "mac_address: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mac_address);
    s << indent << "rssi: ";
    Printer<int16_t>::stream(s, indent + "  ", v.rssi);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BLE_SCANNER_MESSAGE_BLEBEACON_H
