"""autogenerated by genpy from arf_msgs/imuRaw.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class imuRaw(genpy.Message):
  _md5sum = "5eb268536d2c65c632dfa193105c79b1"
  _type = "arf_msgs/imuRaw"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
geometry_msgs/Vector3 accelerometer
geometry_msgs/Vector3 magnetometer
geometry_msgs/Vector3 gyroscope
geometry_msgs/Vector3 RPY

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 

float64 x
float64 y
float64 z
"""
  __slots__ = ['header','accelerometer','magnetometer','gyroscope','RPY']
  _slot_types = ['std_msgs/Header','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,accelerometer,magnetometer,gyroscope,RPY

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(imuRaw, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.accelerometer is None:
        self.accelerometer = geometry_msgs.msg.Vector3()
      if self.magnetometer is None:
        self.magnetometer = geometry_msgs.msg.Vector3()
      if self.gyroscope is None:
        self.gyroscope = geometry_msgs.msg.Vector3()
      if self.RPY is None:
        self.RPY = geometry_msgs.msg.Vector3()
    else:
      self.header = std_msgs.msg.Header()
      self.accelerometer = geometry_msgs.msg.Vector3()
      self.magnetometer = geometry_msgs.msg.Vector3()
      self.gyroscope = geometry_msgs.msg.Vector3()
      self.RPY = geometry_msgs.msg.Vector3()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_12d.pack(_x.accelerometer.x, _x.accelerometer.y, _x.accelerometer.z, _x.magnetometer.x, _x.magnetometer.y, _x.magnetometer.z, _x.gyroscope.x, _x.gyroscope.y, _x.gyroscope.z, _x.RPY.x, _x.RPY.y, _x.RPY.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.accelerometer is None:
        self.accelerometer = geometry_msgs.msg.Vector3()
      if self.magnetometer is None:
        self.magnetometer = geometry_msgs.msg.Vector3()
      if self.gyroscope is None:
        self.gyroscope = geometry_msgs.msg.Vector3()
      if self.RPY is None:
        self.RPY = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 96
      (_x.accelerometer.x, _x.accelerometer.y, _x.accelerometer.z, _x.magnetometer.x, _x.magnetometer.y, _x.magnetometer.z, _x.gyroscope.x, _x.gyroscope.y, _x.gyroscope.z, _x.RPY.x, _x.RPY.y, _x.RPY.z,) = _struct_12d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_12d.pack(_x.accelerometer.x, _x.accelerometer.y, _x.accelerometer.z, _x.magnetometer.x, _x.magnetometer.y, _x.magnetometer.z, _x.gyroscope.x, _x.gyroscope.y, _x.gyroscope.z, _x.RPY.x, _x.RPY.y, _x.RPY.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.accelerometer is None:
        self.accelerometer = geometry_msgs.msg.Vector3()
      if self.magnetometer is None:
        self.magnetometer = geometry_msgs.msg.Vector3()
      if self.gyroscope is None:
        self.gyroscope = geometry_msgs.msg.Vector3()
      if self.RPY is None:
        self.RPY = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 96
      (_x.accelerometer.x, _x.accelerometer.y, _x.accelerometer.z, _x.magnetometer.x, _x.magnetometer.y, _x.magnetometer.z, _x.gyroscope.x, _x.gyroscope.y, _x.gyroscope.z, _x.RPY.x, _x.RPY.y, _x.RPY.z,) = _struct_12d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_12d = struct.Struct("<12d")
